const pictures = [
    require("../images/image_4.jpg"),
    require("../images/images(2).jpg"),
    require("../images/image(7).jpg"),
    require("../images/image(8).jpg"),
    require("../images/image(9).jpg"),
    require("../images/image(10).jpg"),
    require("../images/image(11).jpg"),
    require("../images/image(13).jpg"),
    require("../images/image(14).jpg"),
    require("../images/image(15).jpg"),
    require("../images/image(16).jpg"),
    require("../images/image(17).jpg"),
    require("../images/image(19).jpg"),
    require("../images/image(20).jpg"),
    require("../images/image(24).jpg"),
    require("../images/image(26).jpg"),
    require("../images/image(27).jpg"),
    require("../images/image(28).jpg"),
    require("../images/image(31).jpg"),
    require("../images/image(32).jpg"),
    require("../images/image(34).jpg"),
    require("../images/image(35).jpg"),
    require("../images/image(39).jpg"),
    require("../images/image(40).jpg"),
    require("../images/image(42).jpg"),
    require("../images/image(46).jpg"),
    require("../images/image(47).jpg"),
    require("../images/image(48).jpg"),
    require("../images/image(56).jpg"),
    require("../images/image(57).jpg"),
    require("../images/image(59).jpg"),
]

module.exports = pictures

